name: None production pipeline
on:
  [push]

jobs:
  configure:
    name: Configure AWS credentials
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-crendentials@v1
        with:
          aws-region: us-east-1
          roles-to-assume: arn:aws:iam::327360473041:user/github_user
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  install:
    name: install Gatsby
    runs-on: ubuntu-latest
    steps:
      - name: install npm
        run: sudo apt update && sudo apt install nodejs npm
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest

  upload:
    runs-on: ubuntu-latest


